services:
  postgres:
    image: postgres:16
    container_name: order-management-postgres
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
    ports:
      - "5433:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: orders-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: orders-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: orders-zookeeper:2181
      # Host machine access
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # Container listens on all interfaces
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1